-- ============================================
-- TechSupport Pro - SCRIPT DE IMPLANTAÇÃO COMPLETA
-- Copie tudo e cole no SQL Editor do Supabase
-- ============================================

-- 1. CRIANDO AS TABELAS
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'tech' CHECK (role IN ('admin', 'tech', 'user')),
  phone TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  allowed_categories JSONB DEFAULT '[]'::jsonb,
  allowed_statuses JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT NOT NULL UNIQUE,
  subject TEXT NOT NULL,
  category TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('critical', 'high', 'medium', 'low')),
  status TEXT NOT NULL DEFAULT 'open',
  description TEXT DEFAULT '',
  created_by UUID REFERENCES auth.users ON DELETE SET NULL,
  assigned_to UUID REFERENCES auth.users ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT (NOW() - INTERVAL '3 days'),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  actions_taken TEXT DEFAULT ''
);

-- 2. POPULANDO CATEGORIAS
INSERT INTO categories (name, slug) VALUES 
('Informática/TI', 'ti'),
('Elétrica', 'electrical'),
('Predial/Civil', 'building'),
('Segurança Eletrônica', 'security'),
('Telecomunicações', 'telecom')
ON CONFLICT (slug) DO NOTHING;

-- 3. POPULANDO STATUS
INSERT INTO statuses (name, slug) VALUES 
('Aberto', 'open'),
('Em Atendimento', 'in-progress'),
('Aguardando Peças', 'waiting'),
('Resolvido', 'resolved'),
('Fechado', 'closed')
ON CONFLICT (slug) DO NOTHING;

-- 4. POPULANDO DADOS DE EXEMPLO (SEED)
INSERT INTO tickets (ticket_id, subject, category, priority, status, description, created_at) VALUES 
('#TK-1001', 'Servidor de Arquivos Offline', 'ti', 'critical', 'in-progress', 'O servidor principal parou de responder às 08:00.', NOW() - INTERVAL '2 hours'),
('#TK-1002', 'Lâmpadas Queimadas Bloco C', 'electrical', 'low', 'open', 'Trocar 4 lâmpadas de LED no corredor do segundo andar.', NOW() - INTERVAL '5 hours'),
('#TK-1003', 'Ar Condicionado Vazando', 'building', 'medium', 'waiting', 'Vazamento de água na recepção.', NOW() - INTERVAL '1 day'),
('#TK-1004', 'Câmera de Segurança com Interferência', 'security', 'high', 'open', 'Câmera da entrada principal apresentando chuviscos.', NOW() - INTERVAL '12 hours'),
('#TK-1005', 'Internet Lenta no RH', 'telecom', 'medium', 'resolved', 'Realizado reset no switch e normalizado.', NOW() - INTERVAL '2 days'),
('#TK-1006', 'Troca de Tomadas Sala 12', 'electrical', 'medium', 'closed', 'Tomadas substituídas por padrão novo.', NOW() - INTERVAL '4 days'),
('#TK-1007', 'Configuração de Novo Notebook', 'ti', 'low', 'open', 'Preparar máquina para novo funcionário.', NOW() - INTERVAL '1 hour'),
('#TK-1008', 'Portão Eletrônico Travado', 'security', 'high', 'in-progress', 'Motor do portão não aciona.', NOW() - INTERVAL '3 hours'),
('#TK-1009', 'Infiltração no Teto do Almoxarifado', 'building', 'critical', 'open', 'Risco de molhar materiais sensíveis.', NOW() - INTERVAL '30 minutes'),
('#TK-1010', 'Ramal 402 sem Sinal', 'telecom', 'low', 'resolved', 'Cabo estava desconectado.', NOW() - INTERVAL '1 day')
ON CONFLICT (ticket_id) DO NOTHING;

-- 5. TRIGGER PARA PERFIS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data ->> 'name', split_part(NEW.email, '@', 1)), NEW.email, COALESCE(NEW.raw_user_meta_data ->> 'role', 'tech'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
