-- ============================================
-- TechSupport Pro - Supabase Schema (VERSÃO SIMPLIFICADA)
-- Execute este SQL no Editor SQL do Supabase
-- ============================================

-- 1. TABELAS BÁSICAS
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'tech',
  phone TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  allowed_categories JSONB DEFAULT '[]'::jsonb,
  allowed_statuses JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ATUALIZAR CONSTRAINT DE ROLE (SE EXISTIR)
-- Tentamos remover e adicionar novamente para garantir os novos cargos
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('admin', 'tech', 'client'));

-- 3. TABELAS DE DADOS
CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT NOT NULL UNIQUE,
  subject TEXT NOT NULL,
  category TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('critical', 'high', 'medium', 'low')),
  status TEXT NOT NULL DEFAULT 'open',
  description TEXT DEFAULT '',
  created_by UUID REFERENCES auth.users ON DELETE SET NULL,
  assigned_to UUID REFERENCES auth.users ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  actions_taken TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  notif_new_ticket BOOLEAN DEFAULT true,
  notif_status_change BOOLEAN DEFAULT true,
  notif_sla BOOLEAN DEFAULT true,
  notif_comments BOOLEAN DEFAULT true,
  notif_reports BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS appearance_preferences (
  user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  dark_mode BOOLEAN DEFAULT false,
  compact_mode BOOLEAN DEFAULT false,
  mono_font BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS system_config (
  id INT PRIMARY KEY DEFAULT 1,
  title TEXT NOT NULL DEFAULT 'TechSupport Pro',
  subtitle TEXT NOT NULL DEFAULT 'Enterprise Console',
  logo_url TEXT DEFAULT '',
  CONSTRAINT one_row CHECK (id = 1)
);

-- 4. HABILITAR RLS
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE appearance_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_config ENABLE ROW LEVEL SECURITY;

-- 5. LIMPAR POLÍTICAS (PREVENIR ERRO DE DUPLICIDADE)
DROP POLICY IF EXISTS "authenticated_read_categories" ON categories;
DROP POLICY IF EXISTS "admin_write_categories" ON categories;
DROP POLICY IF EXISTS "admin_delete_categories" ON categories;
DROP POLICY IF EXISTS "authenticated_read_statuses" ON statuses;
DROP POLICY IF EXISTS "admin_write_statuses" ON statuses;
DROP POLICY IF EXISTS "admin_delete_statuses" ON statuses;
DROP POLICY IF EXISTS "authenticated_read_profiles" ON profiles;
DROP POLICY IF EXISTS "user_update_own_profile" ON profiles;
DROP POLICY IF EXISTS "admin_insert_profiles" ON profiles;
DROP POLICY IF EXISTS "admin_update_profiles" ON profiles;
DROP POLICY IF EXISTS "admin_delete_profiles" ON profiles;
DROP POLICY IF EXISTS "authenticated_read_tickets" ON tickets;
DROP POLICY IF EXISTS "authenticated_insert_tickets" ON tickets;
DROP POLICY IF EXISTS "write_own_or_assigned_tickets" ON tickets;
DROP POLICY IF EXISTS "admin_delete_tickets" ON tickets;
DROP POLICY IF EXISTS "user_read_own_notif_prefs" ON notification_preferences;
DROP POLICY IF EXISTS "user_upsert_own_notif_prefs" ON notification_preferences;
DROP POLICY IF EXISTS "user_update_own_notif_prefs" ON notification_preferences;
DROP POLICY IF EXISTS "user_read_own_appearance" ON appearance_preferences;
DROP POLICY IF EXISTS "user_upsert_own_appearance" ON appearance_preferences;
DROP POLICY IF EXISTS "user_update_own_appearance" ON appearance_preferences;
DROP POLICY IF EXISTS "authenticated_read_system_config" ON system_config;
DROP POLICY IF EXISTS "admin_write_system_config" ON system_config;
DROP POLICY IF EXISTS "admin_update_system_config" ON system_config;

-- 6. RE-CRIAR POLÍTICAS
CREATE POLICY "authenticated_read_categories" ON categories FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "admin_write_categories" ON categories FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "admin_delete_categories" ON categories FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "authenticated_read_statuses" ON statuses FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "admin_write_statuses" ON statuses FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "admin_delete_statuses" ON statuses FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "authenticated_read_profiles" ON profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "user_update_own_profile" ON profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "admin_insert_profiles" ON profiles FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "admin_update_profiles" ON profiles FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')) WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "admin_delete_profiles" ON profiles FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "authenticated_read_tickets" ON tickets FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "authenticated_insert_tickets" ON tickets FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "write_own_or_assigned_tickets" ON tickets FOR UPDATE USING (auth.uid() = created_by OR auth.uid() = assigned_to OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "admin_delete_tickets" ON tickets FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "user_read_own_notif_prefs" ON notification_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_upsert_own_notif_prefs" ON notification_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_update_own_notif_prefs" ON notification_preferences FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user_read_own_appearance" ON appearance_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_upsert_own_appearance" ON appearance_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_update_own_appearance" ON appearance_preferences FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "authenticated_read_system_config" ON system_config FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "admin_write_system_config" ON system_config FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "admin_update_system_config" ON system_config FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')) WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- 7. FUNÇÃO E TRIGGER DE AUTO-PERFIL
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'role', 'tech')
  );
  INSERT INTO public.notification_preferences (user_id) VALUES (NEW.id);
  INSERT INTO public.appearance_preferences (user_id) VALUES (NEW.id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
